version: 2
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:8.10-alpine
    
jobs:

  build:
    <<: *defaults
    steps:
      - checkout

  one-for-all:
    <<: *defaults
    steps:
      - run:
          # This is universal for all project for all languages
          name: execute one-for-all
          command: |
            echo "Running one-for-all ..."

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            apk add --update openssl
            wget https://github.com/apex/apex/releases/download/v0.16.0/apex_linux_amd64 -O ./apex
            chmod +x ./apex
            ls -l .
            ./apex
            ./apex deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - one-for-all:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master 
          requires:
            - build
