version: 2
defaults: &defaults
  working_directory: /tmp/app
  docker:
      - image: 421990735784.dkr.ecr.us-east-1.amazonaws.com/ci-build-environment:node-10
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    
jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp/app
          paths:
            - .

  one-for-all:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/app
      - run:
          # This is universal for all project for all languages
          name: execute one-for-all
          command: |
            echo "Running one-for-all ..."

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/app
      - run:
          command: |
            wget https://github.com/apex/apex/releases/download/v0.16.0/apex_linux_amd64 -O ./apex
            chmod +x ./apex
            ls -l .
            ./apex
            ./apex deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - one-for-all:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master 
          requires:
            - build
